#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: LOCLET

# Tag line
tagline: Entdecke Deine Stadt spielend.

# Description
description: Mit der kostenlosen LOCLET App kannst Du an jeder Ecke Deiner Stadt spannende Rätsel entdecken, spielen und selbst platzieren.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/loclet/loclet.github.io/master/assets/site/loclet_icon.png

# Configure authors here
authors:
  klaas:
    name: Klaas Klasing
    display_name: Klaas
    avatar: /assets/img/avatars/klaas_128.jpg
  mara:
    name: Mara Maurer
    display_name: Mara
    avatar: /assets/img/avatars/mara_128.jpg
  robert:
    name: Robert Hein
    display_name: Robert
    avatar: /assets/img/avatars/robert_128.jpg

# Put number of loclets here
num_loclets: 5&#x2e;500

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
username:
  dribbble:
  email:
  facebook: LOCLET
  flickr:
  github: 
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: LOCLET
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: loclet

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-48661205-1

# Enter your Facebook site name and app ID to include a page plugin etc.
facebook:
  app_id: 1467545976875896
  page_name: LOCLET

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.loclet.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - CNAME
